=== krlchk/LAB-OOP-2-5-sem/src/main/resources/beer.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified">

    <xs:element name="Beer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="beer" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:ID"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="dark"/>
                                        <xs:enumeration value="light"/>
                                        <xs:enumeration value="lager"/>
                                        <xs:enumeration value="live"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="al">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="alcoholic"/>
                                        <xs:enumeration value="non-alcoholic"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="manufacturer" type="xs:string"/>
                            <xs:element name="ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingredient" type="xs:string"
                                                    maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="chars">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="revolutions" type="xs:float" minOccurs="0"/>
                                        <xs:element name="transparency" type="xs:byte"/>
                                        <xs:element name="filtered">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="yes"/>
                                                    <xs:enumeration value="no"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nutritionalValue" type="xs:byte" minOccurs="0"/>
                                        <xs:element name="bottlingMethod">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="volume" type="xs:float"/>
                                                    <xs:element name="material" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== krlchk/LAB-OOP-2-5-sem/src/main/resources/beer.xml
<Beer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="beer.xsd">
    <beer>
        <id>beer1</id>
        <name>Golden Ale</name>
        <type>light</type>
        <al>alcoholic</al>
        <manufacturer>Gold Brewery</manufacturer>
        <ingredients>
            <ingredient>water</ingredient>
            <ingredient>barley malt</ingredient>
            <ingredient>hops</ingredient>
        </ingredients>
        <chars>
            <revolutions>5.2</revolutions>
            <transparency>85</transparency>
            <filtered>yes</filtered>
            <nutritionalValue>43</nutritionalValue>
            <bottlingMethod>
                <volume>0.5</volume>
                <material>glass</material>
            </bottlingMethod>
        </chars>
    </beer>
    <beer>
        <id>beer2</id>
        <name>Dark Stout</name>
        <type>dark</type>
        <al>alcoholic</al>
        <manufacturer>Black Rock Brewery</manufacturer>
        <ingredients>
            <ingredient>water</ingredient>
            <ingredient>roasted barley</ingredient>
            <ingredient>hops</ingredient>
        </ingredients>
        <chars>
            <revolutions>6.0</revolutions>
            <transparency>30</transparency>
            <filtered>no</filtered>
            <nutritionalValue>60</nutritionalValue>
            <bottlingMethod>
                <volume>0.33</volume>
                <material>can</material>
            </bottlingMethod>
        </chars>
    </beer>
    <beer>
        <id>beer3</id>
        <name>Live Lager</name>
        <type>light</type>
        <al>non-alcoholic</al>
        <manufacturer>Fresh Hops Brewery</manufacturer>
        <ingredients>
            <ingredient>water</ingredient>
            <ingredient>wheat malt</ingredient>
            <ingredient>hops</ingredient>
            <ingredient>yeast</ingredient>
        </ingredients>
        <chars>
            <transparency>90</transparency>
            <filtered>yes</filtered>
            <bottlingMethod>
                <volume>1.0</volume>
                <material>plastic</material>
            </bottlingMethod>
        </chars>
    </beer>
</Beer>
